#
language: python

matrix:
  include:
  - sudo: required
    services:
      - docker
    env: PIP=pip

notifications:
  email: false

env:
  global:
  - CIBW_BEFORE_BUILD="yum -y install unixODBC-devel"


script:
  - $PIP install cibuildwheel==1.1.0
  - cibuildwheel --output-dir wheelhouse
  # upload to PyPI
  - python -m pip install twine
  - echo $TWINE_PASSWORD
  - python -m twine upload --repository-url https://test.pypi.org/legacy/ wheelhouse/*cp3*.whl
