#
language: python

matrix:
  include:
  - sudo: required
    services:
      - docker
    env: PIP=pip

notifications:
  email: false

script:
  - $PIP install cibuildwheel==1.0.0
  - cibuildwheel --output-dir wheelhouse
  # upload to PyPI
  - python -m pip install twine
  - python -m twine upload --repository-url https://test.pypi.org/legacy/ wheelhouse/*cp3*.whl
