language: python

matrix:
  include:
  - sudo: required
    services:
      - docker
    env: PIP=pip

python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-4.8
    - g++-4.8
    - unixodbc-dev

env:
  global:
  - CIBW_BEFORE_BUILD="yum -y install unixODBC-devel"

install:
  - python setup.py install

script:
  - $PIP install cibuildwheel==1.1.0
  - cibuildwheel --output-dir wheelhouse
  - python -m pip install twine

after_success:
  - python -m twine upload --skip-existing wheelhouse/*.whl
